/***************************************************************************
 *   Copyright (c) 2026 FuCad contributors                                 *
 *                                                                         *
 *   This file is part of FreeCAD.                                         *
 *                                                                         *
 *   FreeCAD is free software: you can redistribute it and/or modify it    *
 *   under the terms of the GNU Lesser General Public License as           *
 *   published by the Free Software Foundation, either version 2.1 of the  *
 *   License, or (at your option) any later version.                       *
 *                                                                         *
 *   FreeCAD is distributed in the hope that it will be useful, but        *
 *   WITHOUT ANY WARRANTY; without even the implied warranty of            *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU      *
 *   Lesser General Public License for more details.                       *
 *                                                                         *
 *   You should have received a copy of the GNU Lesser General Public      *
 *   License along with FreeCAD. If not, see                               *
 *   <https://www.gnu.org/licenses/>.                                      *
 *                                                                         *
 ***************************************************************************/

// GENERATED FILE - DO NOT EDIT.
//
// Rebuild it with:
//     python src/Tools/ribbon_strings.py
// and check it with:
//     python src/Tools/ribbon_strings.py --check
//
// The ribbon's tab titles, panel captions and button labels live in
// Ribbon/Workspaces/*.json, which lupdate never reads; RibbonManager.cpp shows
// them through QCoreApplication::translate("Ribbon", ...). Listing them here as
// QT_TRANSLATE_NOOP puts them in front of lupdate under that same context, so a
// translator sees them. Nothing reads the array - it exists to be scanned.
//
// TestRibbonStrings.py fails if this file and the JSON disagree.

// QT_TRANSLATE_NOOP comes from qglobal.h, which <QtGlobal> is the header for.
#include <QtGlobal>


namespace
{
// NOLINTNEXTLINE(modernize-avoid-c-arrays,cppcoreguidelines-avoid-c-arrays)
[[maybe_unused]] const char* const ribbonStrings[] = {
    QT_TRANSLATE_NOOP("Ribbon", "3D Milling"),
    QT_TRANSLATE_NOOP("Ribbon", "ASSEMBLE"),
    QT_TRANSLATE_NOOP("Ribbon", "Activate Assembly"),
    QT_TRANSLATE_NOOP("Ribbon", "Align"),
    QT_TRANSLATE_NOOP("Ribbon", "Analyze Mesh"),
    QT_TRANSLATE_NOOP("Ribbon", "Appearance"),
    QT_TRANSLATE_NOOP("Ribbon", "Arc"),
    QT_TRANSLATE_NOOP("Ribbon", "Arc Overlay"),
    QT_TRANSLATE_NOOP("Ribbon", "Arch View"),
    QT_TRANSLATE_NOOP("Ribbon", "Array"),
    QT_TRANSLATE_NOOP("Ribbon", "Axis"),
    QT_TRANSLATE_NOOP("Ribbon", "Balloon"),
    QT_TRANSLATE_NOOP("Ribbon", "Base Flange"),
    QT_TRANSLATE_NOOP("Ribbon", "Base View"),
    QT_TRANSLATE_NOOP("Ribbon", "Bend"),
    QT_TRANSLATE_NOOP("Ribbon", "Bill of Materials"),
    QT_TRANSLATE_NOOP("Ribbon", "Boundary Fill"),
    QT_TRANSLATE_NOOP("Ribbon", "Boundary Layer"),
    QT_TRANSLATE_NOOP("Ribbon", "Break"),
    QT_TRANSLATE_NOOP("Ribbon", "Bridge Curve"),
    QT_TRANSLATE_NOOP("Ribbon", "Broken View"),
    QT_TRANSLATE_NOOP("Ribbon", "CONFIGURE"),
    QT_TRANSLATE_NOOP("Ribbon", "CONSTRAINTS"),
    QT_TRANSLATE_NOOP("Ribbon", "CONSTRUCT"),
    QT_TRANSLATE_NOOP("Ribbon", "CREATE"),
    QT_TRANSLATE_NOOP("Ribbon", "CUSTOMIZE"),
    QT_TRANSLATE_NOOP("Ribbon", "Calibrate Canvas"),
    QT_TRANSLATE_NOOP("Ribbon", "Canvas"),
    QT_TRANSLATE_NOOP("Ribbon", "Centerline"),
    QT_TRANSLATE_NOOP("Ribbon", "Centrifugal"),
    QT_TRANSLATE_NOOP("Ribbon", "Chamfer"),
    QT_TRANSLATE_NOOP("Ribbon", "Change Value"),
    QT_TRANSLATE_NOOP("Ribbon", "Check Geometry"),
    QT_TRANSLATE_NOOP("Ribbon", "Check Job"),
    QT_TRANSLATE_NOOP("Ribbon", "Check Solid"),
    QT_TRANSLATE_NOOP("Ribbon", "Circle"),
    QT_TRANSLATE_NOOP("Ribbon", "Circular Pattern"),
    QT_TRANSLATE_NOOP("Ribbon", "Clear Mesh"),
    QT_TRANSLATE_NOOP("Ribbon", "Clip Group"),
    QT_TRANSLATE_NOOP("Ribbon", "Clone Body"),
    QT_TRANSLATE_NOOP("Ribbon", "Close Holes"),
    QT_TRANSLATE_NOOP("Ribbon", "Coil"),
    QT_TRANSLATE_NOOP("Ribbon", "Coincident"),
    QT_TRANSLATE_NOOP("Ribbon", "Combine"),
    QT_TRANSLATE_NOOP("Ribbon", "Comment"),
    QT_TRANSLATE_NOOP("Ribbon", "Compound"),
    QT_TRANSLATE_NOOP("Ribbon", "Compute All"),
    QT_TRANSLATE_NOOP("Ribbon", "Conic Curve"),
    QT_TRANSLATE_NOOP("Ribbon", "Construction Geometry"),
    QT_TRANSLATE_NOOP("Ribbon", "Contact"),
    QT_TRANSLATE_NOOP("Ribbon", "Copy"),
    QT_TRANSLATE_NOOP("Ribbon", "Corner Relief"),
    QT_TRANSLATE_NOOP("Ribbon", "Cosmetic Circle"),
    QT_TRANSLATE_NOOP("Ribbon", "Cosmetic Line"),
    QT_TRANSLATE_NOOP("Ribbon", "Cosmetic Vertex"),
    QT_TRANSLATE_NOOP("Ribbon", "Create Sketch"),
    QT_TRANSLATE_NOOP("Ribbon", "Curvature Comb Analysis"),
    QT_TRANSLATE_NOOP("Ribbon", "Cut Functions"),
    QT_TRANSLATE_NOOP("Ribbon", "DIMENSIONS"),
    QT_TRANSLATE_NOOP("Ribbon", "DRAWING"),
    QT_TRANSLATE_NOOP("Ribbon", "Data Along Line"),
    QT_TRANSLATE_NOOP("Ribbon", "Degrees Of Freedom"),
    QT_TRANSLATE_NOOP("Ribbon", "Delete"),
    QT_TRANSLATE_NOOP("Ribbon", "Delete Face"),
    QT_TRANSLATE_NOOP("Ribbon", "Delete Faces"),
    QT_TRANSLATE_NOOP("Ribbon", "Detail View"),
    QT_TRANSLATE_NOOP("Ribbon", "Dimension"),
    QT_TRANSLATE_NOOP("Ribbon", "Dimension Types"),
    QT_TRANSLATE_NOOP("Ribbon", "Displacement"),
    QT_TRANSLATE_NOOP("Ribbon", "Draft"),
    QT_TRANSLATE_NOOP("Ribbon", "Draft View"),
    QT_TRANSLATE_NOOP("Ribbon", "Dressup"),
    QT_TRANSLATE_NOOP("Ribbon", "Drilling"),
    QT_TRANSLATE_NOOP("Ribbon", "Ellipse"),
    QT_TRANSLATE_NOOP("Ribbon", "Engrave"),
    QT_TRANSLATE_NOOP("Ribbon", "Equal"),
    QT_TRANSLATE_NOOP("Ribbon", "Exploded View"),
    QT_TRANSLATE_NOOP("Ribbon", "Export DXF"),
    QT_TRANSLATE_NOOP("Ribbon", "Export Mesh"),
    QT_TRANSLATE_NOOP("Ribbon", "Export SVG"),
    QT_TRANSLATE_NOOP("Ribbon", "Export Template"),
    QT_TRANSLATE_NOOP("Ribbon", "Extend"),
    QT_TRANSLATE_NOOP("Ribbon", "Extent Dimension"),
    QT_TRANSLATE_NOOP("Ribbon", "Extrude"),
    QT_TRANSLATE_NOOP("Ribbon", "FINISH SKETCH"),
    QT_TRANSLATE_NOOP("Ribbon", "Fillet"),
    QT_TRANSLATE_NOOP("Ribbon", "Finish Sketch"),
    QT_TRANSLATE_NOOP("Ribbon", "Fix / UnFix"),
    QT_TRANSLATE_NOOP("Ribbon", "Fixed"),
    QT_TRANSLATE_NOOP("Ribbon", "Fixture"),
    QT_TRANSLATE_NOOP("Ribbon", "Flange"),
    QT_TRANSLATE_NOOP("Ribbon", "Flip Normals"),
    QT_TRANSLATE_NOOP("Ribbon", "Fluid Material"),
    QT_TRANSLATE_NOOP("Ribbon", "Force"),
    QT_TRANSLATE_NOOP("Ribbon", "Geometric Hatch"),
    QT_TRANSLATE_NOOP("Ribbon", "Gravity"),
    QT_TRANSLATE_NOOP("Ribbon", "Grid"),
    QT_TRANSLATE_NOOP("Ribbon", "Ground"),
    QT_TRANSLATE_NOOP("Ribbon", "Group"),
    QT_TRANSLATE_NOOP("Ribbon", "Harmonize Normals"),
    QT_TRANSLATE_NOOP("Ribbon", "Hatch"),
    QT_TRANSLATE_NOOP("Ribbon", "Heat Flux"),
    QT_TRANSLATE_NOOP("Ribbon", "Hem"),
    QT_TRANSLATE_NOOP("Ribbon", "Hole"),
    QT_TRANSLATE_NOOP("Ribbon", "Horizontal / Vertical"),
    QT_TRANSLATE_NOOP("Ribbon", "INSERT"),
    QT_TRANSLATE_NOOP("Ribbon", "INSPECT"),
    QT_TRANSLATE_NOOP("Ribbon", "Image"),
    QT_TRANSLATE_NOOP("Ribbon", "Insert"),
    QT_TRANSLATE_NOOP("Ribbon", "Insert CAD File"),
    QT_TRANSLATE_NOOP("Ribbon", "Insert Component"),
    QT_TRANSLATE_NOOP("Ribbon", "Insert Derive"),
    QT_TRANSLATE_NOOP("Ribbon", "Insert Mesh"),
    QT_TRANSLATE_NOOP("Ribbon", "Inspect G-code"),
    QT_TRANSLATE_NOOP("Ribbon", "Join Curves"),
    QT_TRANSLATE_NOOP("Ribbon", "Joint"),
    QT_TRANSLATE_NOOP("Ribbon", "Leader"),
    QT_TRANSLATE_NOOP("Ribbon", "Line"),
    QT_TRANSLATE_NOOP("Ribbon", "Line Style"),
    QT_TRANSLATE_NOOP("Ribbon", "Loft"),
    QT_TRANSLATE_NOOP("Ribbon", "Look At Sketch"),
    QT_TRANSLATE_NOOP("Ribbon", "MACRO"),
    QT_TRANSLATE_NOOP("Ribbon", "MANUFACTURE"),
    QT_TRANSLATE_NOOP("Ribbon", "MATERIALS"),
    QT_TRANSLATE_NOOP("Ribbon", "MESH"),
    QT_TRANSLATE_NOOP("Ribbon", "MILLING"),
    QT_TRANSLATE_NOOP("Ribbon", "MODIFY"),
    QT_TRANSLATE_NOOP("Ribbon", "Manage Materials"),
    QT_TRANSLATE_NOOP("Ribbon", "Mass Properties"),
    QT_TRANSLATE_NOOP("Ribbon", "Material Editor"),
    QT_TRANSLATE_NOOP("Ribbon", "Measure"),
    QT_TRANSLATE_NOOP("Ribbon", "Mesh From Shape"),
    QT_TRANSLATE_NOOP("Ribbon", "Mesh Group"),
    QT_TRANSLATE_NOOP("Ribbon", "Mesh Info"),
    QT_TRANSLATE_NOOP("Ribbon", "Mesh Refinement"),
    QT_TRANSLATE_NOOP("Ribbon", "Mesh With Netgen"),
    QT_TRANSLATE_NOOP("Ribbon", "Mesh from Solid"),
    QT_TRANSLATE_NOOP("Ribbon", "Mirror"),
    QT_TRANSLATE_NOOP("Ribbon", "Motion Study"),
    QT_TRANSLATE_NOOP("Ribbon", "Move"),
    QT_TRANSLATE_NOOP("Ribbon", "Move / Copy"),
    QT_TRANSLATE_NOOP("Ribbon", "Move Face"),
    QT_TRANSLATE_NOOP("Ribbon", "New Assembly"),
    QT_TRANSLATE_NOOP("Ribbon", "New Body"),
    QT_TRANSLATE_NOOP("Ribbon", "New Component"),
    QT_TRANSLATE_NOOP("Ribbon", "New Drawing"),
    QT_TRANSLATE_NOOP("Ribbon", "New Drawing From Template"),
    QT_TRANSLATE_NOOP("Ribbon", "New Study"),
    QT_TRANSLATE_NOOP("Ribbon", "Nonlinear Material"),
    QT_TRANSLATE_NOOP("Ribbon", "OUTPUT"),
    QT_TRANSLATE_NOOP("Ribbon", "Offset"),
    QT_TRANSLATE_NOOP("Ribbon", "Offset Face"),
    QT_TRANSLATE_NOOP("Ribbon", "Offset Plane"),
    QT_TRANSLATE_NOOP("Ribbon", "Parallel"),
    QT_TRANSLATE_NOOP("Ribbon", "Patch"),
    QT_TRANSLATE_NOOP("Ribbon", "Pattern"),
    QT_TRANSLATE_NOOP("Ribbon", "Perpendicular"),
    QT_TRANSLATE_NOOP("Ribbon", "Physical Material"),
    QT_TRANSLATE_NOOP("Ribbon", "Plain Annotation"),
    QT_TRANSLATE_NOOP("Ribbon", "Point"),
    QT_TRANSLATE_NOOP("Ribbon", "Point On Object"),
    QT_TRANSLATE_NOOP("Ribbon", "Polygon"),
    QT_TRANSLATE_NOOP("Ribbon", "Polyline"),
    QT_TRANSLATE_NOOP("Ribbon", "Post Process"),
    QT_TRANSLATE_NOOP("Ribbon", "Post Selected"),
    QT_TRANSLATE_NOOP("Ribbon", "Press Pull"),
    QT_TRANSLATE_NOOP("Ribbon", "Pressure"),
    QT_TRANSLATE_NOOP("Ribbon", "Primitive"),
    QT_TRANSLATE_NOOP("Ribbon", "Print"),
    QT_TRANSLATE_NOOP("Ribbon", "Project"),
    QT_TRANSLATE_NOOP("Ribbon", "Project / Include"),
    QT_TRANSLATE_NOOP("Ribbon", "Projected View"),
    QT_TRANSLATE_NOOP("Ribbon", "Purge Results"),
    QT_TRANSLATE_NOOP("Ribbon", "RESULTS"),
    QT_TRANSLATE_NOOP("Ribbon", "Rectangle"),
    QT_TRANSLATE_NOOP("Ribbon", "Rectangular Pattern"),
    QT_TRANSLATE_NOOP("Ribbon", "Refraction"),
    QT_TRANSLATE_NOOP("Ribbon", "Reinforced Material"),
    QT_TRANSLATE_NOOP("Ribbon", "Remove"),
    QT_TRANSLATE_NOOP("Ribbon", "Remove Axes Alignment"),
    QT_TRANSLATE_NOOP("Ribbon", "Remove Cosmetic"),
    QT_TRANSLATE_NOOP("Ribbon", "Rendering Order"),
    QT_TRANSLATE_NOOP("Ribbon", "Repair Dimension"),
    QT_TRANSLATE_NOOP("Ribbon", "Restore Internal Geometry"),
    QT_TRANSLATE_NOOP("Ribbon", "Result Pipeline"),
    QT_TRANSLATE_NOOP("Ribbon", "Revolve"),
    QT_TRANSLATE_NOOP("Ribbon", "Roll To Here"),
    QT_TRANSLATE_NOOP("Ribbon", "SELECT"),
    QT_TRANSLATE_NOOP("Ribbon", "SETUP"),
    QT_TRANSLATE_NOOP("Ribbon", "SHEET METAL"),
    QT_TRANSLATE_NOOP("Ribbon", "SIMULATION"),
    QT_TRANSLATE_NOOP("Ribbon", "SKETCH"),
    QT_TRANSLATE_NOOP("Ribbon", "SOLID"),
    QT_TRANSLATE_NOOP("Ribbon", "STUDY"),
    QT_TRANSLATE_NOOP("Ribbon", "SURFACE"),
    QT_TRANSLATE_NOOP("Ribbon", "Scale"),
    QT_TRANSLATE_NOOP("Ribbon", "Search Commands"),
    QT_TRANSLATE_NOOP("Ribbon", "Section Analysis"),
    QT_TRANSLATE_NOOP("Ribbon", "Section View"),
    QT_TRANSLATE_NOOP("Ribbon", "Select All"),
    QT_TRANSLATE_NOOP("Ribbon", "Select Other"),
    QT_TRANSLATE_NOOP("Ribbon", "Selection Filters"),
    QT_TRANSLATE_NOOP("Ribbon", "Setup"),
    QT_TRANSLATE_NOOP("Ribbon", "Shape Binder"),
    QT_TRANSLATE_NOOP("Ribbon", "Shell"),
    QT_TRANSLATE_NOOP("Ribbon", "Show Results"),
    QT_TRANSLATE_NOOP("Ribbon", "Simple Copy"),
    QT_TRANSLATE_NOOP("Ribbon", "Simulate"),
    QT_TRANSLATE_NOOP("Ribbon", "Sketch Axes"),
    QT_TRANSLATE_NOOP("Ribbon", "Sketch Dimension"),
    QT_TRANSLATE_NOOP("Ribbon", "Sketch Elements"),
    QT_TRANSLATE_NOOP("Ribbon", "Sketch Scale"),
    QT_TRANSLATE_NOOP("Ribbon", "Slot"),
    QT_TRANSLATE_NOOP("Ribbon", "Snap"),
    QT_TRANSLATE_NOOP("Ribbon", "Solid Material"),
    QT_TRANSLATE_NOOP("Ribbon", "Solve"),
    QT_TRANSLATE_NOOP("Ribbon", "Solve Assembly"),
    QT_TRANSLATE_NOOP("Ribbon", "Solver"),
    QT_TRANSLATE_NOOP("Ribbon", "Solver Settings"),
    QT_TRANSLATE_NOOP("Ribbon", "Spline"),
    QT_TRANSLATE_NOOP("Ribbon", "Spline Information"),
    QT_TRANSLATE_NOOP("Ribbon", "Spring"),
    QT_TRANSLATE_NOOP("Ribbon", "Stacking"),
    QT_TRANSLATE_NOOP("Ribbon", "Stop"),
    QT_TRANSLATE_NOOP("Ribbon", "Sub-Shape Binder"),
    QT_TRANSLATE_NOOP("Ribbon", "Surface Finish"),
    QT_TRANSLATE_NOOP("Ribbon", "Sweep"),
    QT_TRANSLATE_NOOP("Ribbon", "Symbol"),
    QT_TRANSLATE_NOOP("Ribbon", "Symmetry"),
    QT_TRANSLATE_NOOP("Ribbon", "Table View"),
    QT_TRANSLATE_NOOP("Ribbon", "Tangent"),
    QT_TRANSLATE_NOOP("Ribbon", "Temperature"),
    QT_TRANSLATE_NOOP("Ribbon", "Text"),
    QT_TRANSLATE_NOOP("Ribbon", "Tie"),
    QT_TRANSLATE_NOOP("Ribbon", "Toggle Constraint"),
    QT_TRANSLATE_NOOP("Ribbon", "Toggle Frames"),
    QT_TRANSLATE_NOOP("Ribbon", "Toggle Grid"),
    QT_TRANSLATE_NOOP("Ribbon", "Toggle Operation"),
    QT_TRANSLATE_NOOP("Ribbon", "Tool Dock"),
    QT_TRANSLATE_NOOP("Ribbon", "Tool Library"),
    QT_TRANSLATE_NOOP("Ribbon", "Trim"),
    QT_TRANSLATE_NOOP("Ribbon", "UTILITIES"),
    QT_TRANSLATE_NOOP("Ribbon", "UTILITY"),
    QT_TRANSLATE_NOOP("Ribbon", "Unfold"),
    QT_TRANSLATE_NOOP("Ribbon", "Update Drawing"),
    QT_TRANSLATE_NOOP("Ribbon", "User Coordinate System"),
    QT_TRANSLATE_NOOP("Ribbon", "Virtual Space"),
    QT_TRANSLATE_NOOP("Ribbon", "Warp"),
    QT_TRANSLATE_NOOP("Ribbon", "Weld Symbol"),
    QT_TRANSLATE_NOOP("Ribbon", "Window Selection"),
    QT_TRANSLATE_NOOP("Ribbon", "Window Selection (Elements)"),
};
}  // namespace
